baseURL = 'https://dsgt-arc.org/'
languageCode = 'en-us'
title = 'DS@GT ARC'
theme = 'hugo-bearblog'

[params]
  description = "Data Science at Georgia Tech - Applied Research Competitions"
  title = "DS@GT ARC"
  hideMadeWithLine = true

[menu]
  [[menu.main]]
    name = "Notes"
    url = "https://notes.dsgt-arc.org"
    weight = 15

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'