baseURL = 'https://dsgt-arc.org/'
languageCode = 'en-us'
title = 'DS@GT ARC'
theme = 'hugo-bearblog'

[params]
  description = "Data Science at Georgia Tech - Applied Research Competitions"
  title = "DS@GT ARC"
  hideMadeWithLine = true

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true