name = "dsgt-arc"
compatibility_date = "2025-06-12"
preview_urls = true
routes = [
  { pattern = "dsgt-arc.org", custom_domain = true },
  { pattern = "www.dsgt-arc.org", custom_domain = true }
]

[assets]
directory = "./public"
